// List of spawnable DayZ items for the shop with average costs (customize as needed)
// Format: { name, class, averagePrice, description }

module.exports = [
  { name: 'M4A1 Assault Rifle', class: 'M4A1', averagePrice: 1200, description: 'Standard 5.56mm assault rifle.' },
  { name: 'AKM', class: 'AKM', averagePrice: 1100, description: '7.62mm classic assault rifle.' },
  { name: 'Mosin Nagant', class: 'Mosin9130', averagePrice: 900, description: 'Bolt-action sniper rifle.' },
  { name: 'SVD', class: 'SVD', averagePrice: 2000, description: 'Rare semi-auto sniper rifle.' },
  { name: 'LAR', class: 'FAL', averagePrice: 1800, description: 'Battle rifle, high damage.' },
  { name: 'Winchester 70', class: 'Winchester70', averagePrice: 950, description: 'Hunting bolt-action rifle.' },
  { name: 'BK-133 Shotgun', class: 'Mp133Shotgun', averagePrice: 600, description: 'Pump-action shotgun.' },
  { name: 'IZH-18 Rifle', class: 'Izh18', averagePrice: 350, description: 'Single-shot rifle.' },
  { name: 'CR-527', class: 'CZ527', averagePrice: 800, description: 'Bolt-action carbine.' },
  { name: 'USG-45', class: 'UMP45', averagePrice: 850, description: '45 ACP submachine gun.' },
  { name: 'SG5-K', class: 'MP5K', averagePrice: 800, description: '9mm submachine gun.' },
  { name: 'Glock 19', class: 'Glock19', averagePrice: 400, description: '9mm semi-auto pistol.' },
  { name: 'IJ-70', class: 'IJ70', averagePrice: 300, description: '9mm budget pistol.' },
  { name: 'FX-45', class: 'FNX45', averagePrice: 450, description: '45 ACP pistol.' },
  { name: 'Ammo Box (5.56x45)', class: 'Ammo_556x45', averagePrice: 200, description: 'Box of 5.56mm ammo.' },
  { name: 'Ammo Box (7.62x39)', class: 'Ammo_762x39', averagePrice: 220, description: 'Box of 7.62x39mm ammo.' },
  { name: 'Ammo Box (7.62x54R)', class: 'Ammo_762x54', averagePrice: 250, description: 'Box of 7.62x54R ammo.' },
  { name: 'Ammo Box (9x19mm)', class: 'Ammo_9x19', averagePrice: 120, description: 'Box of 9x19mm ammo.' },
  { name: 'Ammo Box (.45 ACP)', class: 'Ammo_45ACP', averagePrice: 130, description: 'Box of .45 ACP ammo.' },
  { name: 'Plate Carrier', class: 'PlateCarrierVest', averagePrice: 1500, description: 'Heavy armor vest.' },
  { name: 'Assault Backpack (Black)', class: 'AssaultBag_Black', averagePrice: 700, description: 'Large capacity backpack.' },
  { name: 'Assault Backpack (Green)', class: 'AssaultBag_Green', averagePrice: 700, description: 'Large capacity backpack.' },
  { name: 'Coyote Backpack (Brown)', class: 'CoyoteBag_Brown', averagePrice: 600, description: 'Medium capacity backpack.' },
  { name: 'Coyote Backpack (Green)', class: 'CoyoteBag_Green', averagePrice: 600, description: 'Medium capacity backpack.' },
  { name: 'Hunting Backpack', class: 'HuntingBag', averagePrice: 650, description: 'Hunting backpack.' },
  { name: 'Ballistic Helmet (Black)', class: 'BallisticHelmet_Black', averagePrice: 500, description: 'Ballistic helmet.' },
  { name: 'Ballistic Helmet (Green)', class: 'BallisticHelmet_Green', averagePrice: 500, description: 'Ballistic helmet.' },
  { name: 'Tactical Gloves', class: 'TacticalGloves_Black', averagePrice: 150, description: 'Protective gloves.' },
  { name: 'NVG Headstrap', class: 'NVGHeadstrap', averagePrice: 2000, description: 'Night vision headstrap.' },
  { name: 'Night Vision Goggles', class: 'NVGoggles', averagePrice: 3500, description: 'Night vision goggles.' },
  { name: 'Canteen', class: 'Canteen', averagePrice: 80, description: 'Water container.' },
  { name: 'Tetracycline Pills', class: 'TetracyclineAntibiotics', averagePrice: 120, description: 'Antibiotic pills.' },
  { name: 'Epinephrine Auto-Injector', class: 'Epinephrine', averagePrice: 180, description: 'Revives unconscious players.' },
  { name: 'Morphine Auto-Injector', class: 'Morphine', averagePrice: 200, description: 'Heals broken bones.' },
  { name: 'Saline Bag IV', class: 'SalineBagIV', averagePrice: 250, description: 'Restores blood.' },
  { name: 'Bandage', class: 'BandageDressing', averagePrice: 60, description: 'Medical bandage.' },
  { name: 'Lockpick', class: 'Lockpick', averagePrice: 100, description: 'Used to lock doors.' },
  { name: 'Car Battery', class: 'CarBattery', averagePrice: 400, description: 'Vehicle battery.' },
  { name: 'Spark Plug', class: 'SparkPlug', averagePrice: 120, description: 'Vehicle spark plug.' },
  { name: 'Radiator', class: 'CarRadiator', averagePrice: 350, description: 'Vehicle radiator.' },
  { name: 'Jerrycan', class: 'CanisterGasoline', averagePrice: 200, description: 'Fuel container.' },

  // Magazines from types.xml
  { name: '1911 Magazine (7Rnd)', class: 'Mag_1911_7Rnd', averagePrice: 200, description: '7-round magazine for 1911 pistol.' },
  { name: 'AK101 Magazine (30Rnd)', class: 'Mag_AK101_30Rnd', averagePrice: 300, description: '30-round magazine for AK101.' },
  { name: 'AK74 Magazine (30Rnd)', class: 'Mag_AK74_30Rnd', averagePrice: 300, description: '30-round magazine for AK74.' },
  { name: 'AK74 Magazine (45Rnd)', class: 'Mag_AK74_45Rnd', averagePrice: 350, description: '45-round magazine for AK74.' },
  { name: 'AKM Magazine (30Rnd)', class: 'Mag_AKM_30Rnd', averagePrice: 300, description: '30-round magazine for AKM.' },
  { name: 'AKM Drum Magazine (75Rnd)', class: 'Mag_AKM_Drum75Rnd', averagePrice: 600, description: '75-round drum magazine for AKM.' },
  { name: 'AKM Palm Magazine (30Rnd)', class: 'Mag_AKM_Palm30Rnd', averagePrice: 320, description: '30-round palm magazine for AKM.' },
  { name: 'AUG Magazine (30Rnd)', class: 'Mag_Aug_30Rnd', averagePrice: 300, description: '30-round magazine for AUG.' },
  { name: 'CMAG (10Rnd)', class: 'Mag_CMAG_10Rnd', averagePrice: 120, description: '10-round CMAG.' },
  { name: 'CMAG (20Rnd)', class: 'Mag_CMAG_20Rnd', averagePrice: 180, description: '20-round CMAG.' },
  { name: 'CMAG (30Rnd)', class: 'Mag_CMAG_30Rnd', averagePrice: 220, description: '30-round CMAG.' },
  { name: 'CMAG (40Rnd)', class: 'Mag_CMAG_40Rnd', averagePrice: 260, description: '40-round CMAG.' },
  { name: 'CZ527 Magazine (5Rnd)', class: 'Mag_CZ527_5rnd', averagePrice: 150, description: '5-round magazine for CZ527.' },
  { name: 'CZ550 Magazine (10Rnd)', class: 'Mag_CZ550_10Rnd', averagePrice: 180, description: '10-round magazine for CZ550.' },
  { name: 'CZ61 Magazine (20Rnd)', class: 'Mag_CZ61_20Rnd', averagePrice: 180, description: '20-round magazine for CZ61.' },
  { name: 'CZ75 Magazine (15Rnd)', class: 'Mag_CZ75_15Rnd', averagePrice: 180, description: '15-round magazine for CZ75.' },
  { name: 'Deagle Magazine (9Rnd)', class: 'Mag_Deagle_9rnd', averagePrice: 200, description: '9-round magazine for Deagle.' },
  { name: 'FAL Magazine (20Rnd)', class: 'Mag_FAL_20Rnd', averagePrice: 350, description: '20-round magazine for FAL.' },
  { name: 'FAMAS Magazine (25Rnd)', class: 'Mag_FAMAS_25Rnd', averagePrice: 320, description: '25-round magazine for FAMAS.' },
  { name: 'FNX45 Magazine (15Rnd)', class: 'Mag_FNX45_15Rnd', averagePrice: 180, description: '15-round magazine for FNX45.' },
  { name: 'Glock Magazine (15Rnd)', class: 'Mag_Glock_15Rnd', averagePrice: 180, description: '15-round magazine for Glock.' },
  { name: 'IJ70 Magazine (8Rnd)', class: 'Mag_IJ70_8Rnd', averagePrice: 120, description: '8-round magazine for IJ70.' },
  { name: 'M14 Magazine (10Rnd)', class: 'Mag_M14_10Rnd', averagePrice: 200, description: '10-round magazine for M14.' },
  { name: 'M14 Magazine (20Rnd)', class: 'Mag_M14_20Rnd', averagePrice: 250, description: '20-round magazine for M14.' },
  { name: 'MKII Magazine (10Rnd)', class: 'Mag_MKII_10Rnd', averagePrice: 120, description: '10-round magazine for MKII.' },
  { name: 'MP5 Magazine (15Rnd)', class: 'Mag_MP5_15Rnd', averagePrice: 150, description: '15-round magazine for MP5.' },
  { name: 'MP5 Magazine (30Rnd)', class: 'Mag_MP5_30Rnd', averagePrice: 200, description: '30-round magazine for MP5.' },
  { name: 'P1 Magazine (8Rnd)', class: 'Mag_P1_8Rnd', averagePrice: 120, description: '8-round magazine for P1.' },
  { name: 'PM73 Magazine (15Rnd)', class: 'Mag_PM73_15Rnd', averagePrice: 150, description: '15-round magazine for PM73.' },
  { name: 'PM73 Magazine (25Rnd)', class: 'Mag_PM73_25Rnd', averagePrice: 180, description: '25-round magazine for PM73.' },
  { name: 'PP19 Magazine (64Rnd)', class: 'Mag_PP19_64Rnd', averagePrice: 400, description: '64-round magazine for PP19.' },
  { name: 'Ruger 10/22 Magazine (15Rnd)', class: 'Mag_Ruger1022_15Rnd', averagePrice: 120, description: '15-round magazine for Ruger 10/22.' },
  { name: 'Ruger 10/22 Magazine (30Rnd)', class: 'Mag_Ruger1022_30Rnd', averagePrice: 180, description: '30-round magazine for Ruger 10/22.' },
  { name: 'SSG82 Magazine (5Rnd)', class: 'Mag_SSG82_5rnd', averagePrice: 150, description: '5-round magazine for SSG82.' },
  { name: 'STANAG Magazine (30Rnd)', class: 'Mag_STANAG_30Rnd', averagePrice: 220, description: '30-round STANAG magazine.' },
  { name: 'STANAG Magazine (60Rnd)', class: 'Mag_STANAG_60Rnd', averagePrice: 350, description: '60-round STANAG magazine.' },
  { name: 'SV98 Magazine (10Rnd)', class: 'Mag_SV98_10Rnd', averagePrice: 200, description: '10-round magazine for SV98.' },
  { name: 'SVD Magazine (10Rnd)', class: 'Mag_SVD_10Rnd', averagePrice: 250, description: '10-round magazine for SVD.' },
  { name: 'Saiga Magazine (5Rnd)', class: 'Mag_Saiga_5Rnd', averagePrice: 180, description: '5-round magazine for Saiga.' },
  { name: 'Saiga Magazine (8Rnd)', class: 'Mag_Saiga_8Rnd', averagePrice: 220, description: '8-round magazine for Saiga.' },
  { name: 'Saiga Drum Magazine (20Rnd)', class: 'Mag_Saiga_Drum20Rnd', averagePrice: 400, description: '20-round drum magazine for Saiga.' },
  { name: 'Scout Magazine (5Rnd)', class: 'Mag_Scout_5Rnd', averagePrice: 150, description: '5-round magazine for Scout.' },
  { name: 'UMP Magazine (25Rnd)', class: 'Mag_UMP_25Rnd', averagePrice: 200, description: '25-round magazine for UMP.' },
  { name: 'VAL Magazine (20Rnd)', class: 'Mag_VAL_20Rnd', averagePrice: 250, description: '20-round magazine for VAL.' },
  { name: 'VSS Magazine (10Rnd)', class: 'Mag_VSS_10Rnd', averagePrice: 200, description: '10-round magazine for VSS.' },
  { name: 'Vikhr Magazine (30Rnd)', class: 'Mag_Vikhr_30Rnd', averagePrice: 300, description: '30-round magazine for Vikhr.' },
  // End magazines
];
