// List of spawnable DayZ items for the shop with average costs (customize as needed)
// Format: { name, class, averagePrice, description }

module.exports = [
  // --- ASSAULT RIFLES ---
  { name: 'M4A1 Assault Rifle', class: 'M4A1', averagePrice: 1200, description: 'Standard 5.56mm assault rifle.' },
  { name: 'M4A1 (Black)', class: 'M4A1_Black', averagePrice: 1200, description: 'Black 5.56mm assault rifle.' },
  { name: 'M4A1 (Green)', class: 'M4A1_Green', averagePrice: 1200, description: 'Green 5.56mm assault rifle.' },
  { name: 'M16A2', class: 'M16A2', averagePrice: 1300, description: '5.56mm military assault rifle.' },
  { name: 'AK101', class: 'AK101', averagePrice: 1150, description: '5.56mm AK-platform rifle.' },
  { name: 'AK101 (Black)', class: 'AK101_Black', averagePrice: 1150, description: 'Black 5.56mm AK-platform rifle.' },
  { name: 'AK101 (Green)', class: 'AK101_Green', averagePrice: 1150, description: 'Green 5.56mm AK-platform rifle.' },
  { name: 'AK74', class: 'AK74', averagePrice: 1050, description: '5.45mm assault rifle.' },
  { name: 'AK74 (Black)', class: 'AK74_Black', averagePrice: 1050, description: 'Black 5.45mm assault rifle.' },
  { name: 'AK74 (Green)', class: 'AK74_Green', averagePrice: 1050, description: 'Green 5.45mm assault rifle.' },
  { name: 'AKM', class: 'AKM', averagePrice: 1100, description: '7.62mm classic assault rifle.' },
  { name: 'AKS-74U', class: 'AKS74U', averagePrice: 900, description: 'Compact 5.45mm assault rifle.' },
  { name: 'AKS-74U (Black)', class: 'AKS74U_Black', averagePrice: 900, description: 'Black compact 5.45mm assault rifle.' },
  { name: 'AKS-74U (Green)', class: 'AKS74U_Green', averagePrice: 900, description: 'Green compact 5.45mm assault rifle.' },
  { name: 'AUG', class: 'Aug', averagePrice: 1400, description: 'Bullpup 5.56mm assault rifle.' },
  { name: 'AUG Short', class: 'AugShort', averagePrice: 1350, description: 'Compact bullpup 5.56mm rifle.' },
  { name: 'FAMAS', class: 'FAMAS', averagePrice: 1350, description: 'French bullpup assault rifle.' },
  { name: 'LAR', class: 'FAL', averagePrice: 1800, description: 'Battle rifle, high damage.' },
  { name: 'AS VAL', class: 'ASVAL', averagePrice: 1950, description: 'Suppressed Soviet assault rifle.' },
  { name: 'SVAL', class: 'SVAL', averagePrice: 1950, description: 'Suppressed modern assault rifle.' },
  { name: 'VSK-94', class: 'VSK94', averagePrice: 1700, description: 'Suppressed Russian marksman rifle.' },

  // --- SNIPER / MARKSMAN RIFLES ---
  { name: 'Mosin Nagant', class: 'Mosin9130', averagePrice: 900, description: 'Bolt-action sniper rifle.' },
  { name: 'Mosin Nagant (Black)', class: 'Mosin9130_Black', averagePrice: 900, description: 'Black bolt-action sniper rifle.' },
  { name: 'Mosin Nagant (Camo)', class: 'Mosin9130_Camo', averagePrice: 900, description: 'Camo bolt-action sniper rifle.' },
  { name: 'Mosin Nagant (Green)', class: 'Mosin9130_Green', averagePrice: 900, description: 'Green bolt-action sniper rifle.' },
  { name: 'SVD', class: 'SVD', averagePrice: 2000, description: 'Rare semi-auto sniper rifle.' },
  { name: 'SVD (Wooden)', class: 'SVD_Wooden', averagePrice: 2000, description: 'Wooden SVD sniper rifle.' },
  { name: 'VSS', class: 'VSS', averagePrice: 1900, description: 'Suppressed sniper rifle.' },
  { name: 'Winchester 70', class: 'Winchester70', averagePrice: 950, description: 'Hunting bolt-action rifle.' },
  { name: 'CR-527', class: 'CZ527', averagePrice: 800, description: 'Bolt-action carbine.' },
  { name: 'CZ550', class: 'CZ550', averagePrice: 1100, description: 'Hunting bolt-action rifle.' },
  { name: 'Scout', class: 'Scout', averagePrice: 850, description: 'Compact bolt-action rifle.' },
  { name: 'Scout (Chernarus)', class: 'Scout_Chernarus', averagePrice: 850, description: 'Chernarus Scout rifle.' },
  { name: 'Scout (Livonia)', class: 'Scout_Livonia', averagePrice: 850, description: 'Livonia Scout rifle.' },
  { name: 'SSG82', class: 'SSG82', averagePrice: 750, description: 'Soviet training rifle.' },
  { name: 'B95', class: 'B95', averagePrice: 900, description: 'Double-barrel break-action rifle.' },
  { name: 'Blaze 95', class: 'Blaze95', averagePrice: 950, description: 'Double-barrel break-action hunting rifle.' },
  { name: 'M70 Tundra', class: 'M70', averagePrice: 1000, description: 'Bolt-action hunting rifle.' },
  { name: 'SV-98', class: 'SV98', averagePrice: 1800, description: 'Russian bolt-action sniper rifle.' },

  // --- RIFLES ---
  { name: 'SKS', class: 'SKS', averagePrice: 700, description: 'Semi-auto carbine.' },
  { name: 'Repeater', class: 'Repeater', averagePrice: 600, description: 'Lever-action rifle.' },
  { name: 'Ruger 10/22', class: 'Ruger1022', averagePrice: 450, description: '.22 caliber rifle.' },
  { name: 'IZH-18 Rifle', class: 'Izh18', averagePrice: 350, description: 'Single-shot rifle.' },
  { name: 'CR-550', class: 'CR550', averagePrice: 950, description: 'Modern bolt-action hunting rifle.' },

  // --- SHOTGUNS ---
  { name: 'BK-133 Shotgun', class: 'Mp133Shotgun', averagePrice: 600, description: 'Pump-action shotgun.' },
  { name: 'IZH-18 Shotgun', class: 'Izh18Shotgun', averagePrice: 400, description: 'Single-shot shotgun.' },
  { name: 'IZH-43 Shotgun', class: 'Izh43Shotgun', averagePrice: 550, description: 'Double-barrel shotgun.' },
  { name: 'Saiga', class: 'Saiga', averagePrice: 900, description: 'Semi-auto shotgun.' },

  // --- SMGs / PDWs ---
  { name: 'USG-45', class: 'UMP45', averagePrice: 850, description: '45 ACP submachine gun.' },
  { name: 'SG5-K', class: 'MP5K', averagePrice: 800, description: '9mm submachine gun.' },
  { name: 'PP-19', class: 'PP19', averagePrice: 750, description: '9mm submachine gun.' },
  { name: 'PM-73 RAK', class: 'PM73Rak', averagePrice: 650, description: '9mm submachine gun.' },
  { name: 'CZ-61 Skorpion', class: 'CZ61', averagePrice: 550, description: 'Compact machine pistol.' },
  { name: 'Vityaz', class: 'Vityaz', averagePrice: 900, description: '9mm Russian submachine gun.' },

  // --- LAUNCHERS ---
  { name: 'M79 Grenade Launcher', class: 'M79', averagePrice: 2500, description: 'Single-shot 40mm grenade launcher.' },

  // --- PISTOLS ---
  { name: 'Desert Eagle', class: 'Deagle', averagePrice: 800, description: 'Powerful .357 pistol.' },
  { name: 'Desert Eagle (Gold)', class: 'Deagle_Gold', averagePrice: 1200, description: 'Gold-plated Desert Eagle.' },
  { name: 'FX-45', class: 'FNX45', averagePrice: 450, description: '45 ACP pistol.' },
  { name: 'Glock 19', class: 'Glock19', averagePrice: 400, description: '9mm semi-auto pistol.' },
  { name: 'CZ-75', class: 'CZ75', averagePrice: 420, description: '9mm semi-auto pistol.' },
  { name: 'P1', class: 'P1', averagePrice: 350, description: '9mm pistol.' },
  { name: 'IJ-70', class: 'MakarovIJ70', averagePrice: 300, description: '9mm budget pistol.' },
  { name: 'Ruger MK II', class: 'MKII', averagePrice: 280, description: '.22 caliber pistol.' },
  
  // --- AMMUNITION BOXES ---
  { name: 'Ammo Box (.22 LR 50Rnd)', class: 'AmmoBox_22_50Rnd', averagePrice: 80, description: 'Box of 50 .22 LR rounds.' },
  { name: 'Ammo Box (.308 Win 20Rnd)', class: 'AmmoBox_308Win_20Rnd', averagePrice: 220, description: 'Box of 20 .308 Winchester rounds.' },
  { name: 'Ammo Box (.308 Win Tracer 20Rnd)', class: 'AmmoBox_308WinTracer_20Rnd', averagePrice: 240, description: 'Box of 20 .308 tracer rounds.' },
  { name: 'Ammo Box (.357 20Rnd)', class: 'AmmoBox_357_20Rnd', averagePrice: 180, description: 'Box of 20 .357 rounds.' },
  { name: 'Ammo Box (.380 ACP 35Rnd)', class: 'AmmoBox_380_35rnd', averagePrice: 100, description: 'Box of 35 .380 ACP rounds.' },
  { name: 'Ammo Box (.45 ACP 25Rnd)', class: 'AmmoBox_45ACP_25rnd', averagePrice: 130, description: 'Box of 25 .45 ACP rounds.' },
  { name: 'Ammo Box (5.45x39 20Rnd)', class: 'AmmoBox_545x39_20Rnd', averagePrice: 180, description: 'Box of 20 5.45x39mm rounds.' },
  { name: 'Ammo Box (5.45x39 Tracer 20Rnd)', class: 'AmmoBox_545x39Tracer_20Rnd', averagePrice: 200, description: 'Box of 20 5.45x39mm tracer rounds.' },
  { name: 'Ammo Box (5.56x45 20Rnd)', class: 'AmmoBox_556x45_20Rnd', averagePrice: 200, description: 'Box of 20 5.56mm rounds.' },
  { name: 'Ammo Box (5.56x45 Tracer 20Rnd)', class: 'AmmoBox_556x45Tracer_20Rnd', averagePrice: 220, description: 'Box of 20 5.56mm tracer rounds.' },
  { name: 'Ammo Box (7.62x39 20Rnd)', class: 'AmmoBox_762x39_20Rnd', averagePrice: 220, description: 'Box of 20 7.62x39mm rounds.' },
  { name: 'Ammo Box (7.62x39 Tracer 20Rnd)', class: 'AmmoBox_762x39Tracer_20Rnd', averagePrice: 240, description: 'Box of 20 7.62x39mm tracer rounds.' },
  { name: 'Ammo Box (7.62x54R 20Rnd)', class: 'AmmoBox_762x54_20Rnd', averagePrice: 250, description: 'Box of 20 7.62x54R rounds.' },
  { name: 'Ammo Box (7.62x54R Tracer 20Rnd)', class: 'AmmoBox_762x54Tracer_20Rnd', averagePrice: 270, description: 'Box of 20 7.62x54R tracer rounds.' },
  { name: 'Ammo Box (9x19 25Rnd)', class: 'AmmoBox_9x19_25rnd', averagePrice: 120, description: 'Box of 25 9x19mm rounds.' },
  { name: 'Ammo Box (9x39 20Rnd)', class: 'AmmoBox_9x39_20Rnd', averagePrice: 200, description: 'Box of 20 9x39mm rounds.' },
  { name: 'Ammo Box (9x39 AP 20Rnd)', class: 'AmmoBox_9x39AP_20Rnd', averagePrice: 250, description: 'Box of 20 9x39mm armor-piercing rounds.' },
  { name: 'Ammo Box (12ga 00 Buck 10Rnd)', class: 'AmmoBox_00buck_10rnd', averagePrice: 150, description: 'Box of 10 12-gauge buckshot shells.' },
  { name: 'Ammo Box (12ga Slug 10Rnd)', class: 'AmmoBox_12gaSlug_10Rnd', averagePrice: 180, description: 'Box of 10 12-gauge slug shells.' },
  { name: 'Ammo Box (12ga Rubber Slug 10Rnd)', class: 'AmmoBox_12gaRubberSlug_10Rnd', averagePrice: 120, description: 'Box of 10 12-gauge rubber slug shells.' },
  
  // --- GEAR & EQUIPMENT ---
  { name: 'Plate Carrier', class: 'PlateCarrierVest', averagePrice: 1500, description: 'Heavy armor vest.' },
  { name: 'Alice Backpack (Black)', class: 'AliceBag_Black', averagePrice: 800, description: 'Large military backpack, black.' },
  { name: 'Alice Backpack (Camo)', class: 'AliceBag_Camo', averagePrice: 800, description: 'Large military backpack, camo.' },
  { name: 'Alice Backpack (Green)', class: 'AliceBag_Green', averagePrice: 800, description: 'Large military backpack, green.' },
  { name: 'Assault Backpack (Black)', class: 'AssaultBag_Black', averagePrice: 700, description: 'Large capacity backpack.' },
  { name: 'Assault Backpack (Green)', class: 'AssaultBag_Green', averagePrice: 700, description: 'Large capacity backpack.' },
  { name: 'Coyote Backpack (Brown)', class: 'CoyoteBag_Brown', averagePrice: 600, description: 'Medium capacity backpack.' },
  { name: 'Coyote Backpack (Green)', class: 'CoyoteBag_Green', averagePrice: 600, description: 'Medium capacity backpack.' },
  { name: 'Hunting Backpack', class: 'HuntingBag', averagePrice: 650, description: 'Hunting backpack.' },
  { name: 'Ballistic Helmet (Black)', class: 'BallisticHelmet_Black', averagePrice: 500, description: 'Ballistic helmet.' },
  { name: 'Ballistic Helmet (Green)', class: 'BallisticHelmet_Green', averagePrice: 500, description: 'Ballistic helmet.' },
  { name: 'Tactical Gloves', class: 'TacticalGloves_Black', averagePrice: 150, description: 'Protective gloves.' },
  { name: 'NVG Headstrap', class: 'NVGHeadstrap', averagePrice: 2000, description: 'Night vision headstrap.' },
  { name: 'Night Vision Goggles', class: 'NVGoggles', averagePrice: 3500, description: 'Night vision goggles.' },
  { name: 'Canteen', class: 'Canteen', averagePrice: 80, description: 'Water container.' },
  { name: 'Tetracycline Pills', class: 'TetracyclineAntibiotics', averagePrice: 120, description: 'Antibiotic pills.' },
  { name: 'Epinephrine Auto-Injector', class: 'Epinephrine', averagePrice: 180, description: 'Revives unconscious players.' },
  { name: 'Morphine Auto-Injector', class: 'Morphine', averagePrice: 200, description: 'Heals broken bones.' },
  { name: 'Saline Bag IV', class: 'SalineBagIV', averagePrice: 250, description: 'Restores blood.' },
  { name: 'Bandage', class: 'BandageDressing', averagePrice: 60, description: 'Medical bandage.' },
  { name: 'Lockpick', class: 'Lockpick', averagePrice: 100, description: 'Used to lock doors.' },
  
  // Vehicle Parts
  { name: 'Car Battery', class: 'CarBattery', averagePrice: 400, description: 'Vehicle battery.' },
  { name: 'Spark Plug', class: 'SparkPlug', averagePrice: 120, description: 'Vehicle spark plug.' },
  { name: 'Radiator', class: 'CarRadiator', averagePrice: 350, description: 'Vehicle radiator.' },
  { name: 'Jerrycan', class: 'CanisterGasoline', averagePrice: 200, description: 'Fuel container.' },

  // Weapon Attachments - Optics
  { name: 'ACOG Optic', class: 'ACOGOptic', averagePrice: 600, description: '4x magnification optic.' },
  { name: 'ACOG Optic (6x)', class: 'ACOGOptic_6x', averagePrice: 700, description: '6x magnification optic.' },
  { name: 'Reflex Optic', class: 'ReflexOptic', averagePrice: 400, description: 'Red dot sight.' },
  { name: 'M68 Optic', class: 'M68Optic', averagePrice: 450, description: 'Combat red dot sight.' },
  { name: 'Kobra Optic', class: 'KobraOptic', averagePrice: 420, description: 'Russian red dot sight.' },
  { name: 'Kashtan Optic', class: 'KashtanOptic', averagePrice: 650, description: '4x scope with red dot.' },
  { name: 'Kazuar Optic', class: 'KazuarOptic', averagePrice: 700, description: 'High-power optic.' },
  { name: 'PSO-1 Optic', class: 'PSO1Optic', averagePrice: 750, description: 'SVD scope.' },
  { name: 'PSO-6 Optic', class: 'PSO6Optic', averagePrice: 650, description: '4x military scope.' },
  { name: 'PSO-11 Optic', class: 'PSO11Optic', averagePrice: 600, description: 'Military scope.' },
  { name: 'PU Scope', class: 'PUScopeOptic', averagePrice: 500, description: 'Classic sniper scope.' },
  { name: 'Hunting Optic', class: 'HuntingOptic', averagePrice: 550, description: 'Hunting scope.' },
  { name: 'Sporting Optic', class: 'SportingOptic', averagePrice: 480, description: 'Sporting scope.' },
  { name: 'Starlight Optic', class: 'StarlightOptic', averagePrice: 2500, description: 'Night vision scope.' },
  { name: 'BUIS Optic', class: 'BUISOptic', averagePrice: 300, description: 'Backup iron sights.' },
  { name: 'M4 Carry Handle Optic', class: 'M4_CarryHandleOptic', averagePrice: 350, description: 'M4 carry handle sight.' },
  { name: 'M4 T3N RDS Optic', class: 'M4_T3NRDSOptic', averagePrice: 500, description: 'M4 red dot sight.' },
  { name: 'MK4 Optic (Black)', class: 'MK4Optic_Black', averagePrice: 520, description: 'Black MK4 optic.' },
  { name: 'MK4 Optic (Green)', class: 'MK4Optic_Green', averagePrice: 520, description: 'Green MK4 optic.' },
  { name: 'MK4 Optic (Tan)', class: 'MK4Optic_Tan', averagePrice: 520, description: 'Tan MK4 optic.' },
  { name: 'Pistol Optic', class: 'PistolOptic', averagePrice: 350, description: 'Pistol red dot sight.' },
  { name: 'FNP45 MRDS Optic', class: 'FNP45_MRDSOptic', averagePrice: 380, description: 'Mini red dot for FNP45.' },
  
  // Weapon Attachments - Suppressors
  { name: 'AK Suppressor', class: 'AK_Suppressor', averagePrice: 800, description: 'AK sound suppressor.' },
  { name: 'M4 Suppressor', class: 'M4_Suppressor', averagePrice: 800, description: 'M4 sound suppressor.' },
  { name: 'Pistol Suppressor', class: 'PistolSuppressor', averagePrice: 600, description: 'Pistol suppressor.' },
  { name: 'Improvised Suppressor', class: 'ImprovisedSuppressor', averagePrice: 300, description: 'Makeshift suppressor.' },
  
  // Weapon Attachments - Compensators & Bayonets
  { name: 'MP5 Compensator', class: 'MP5_Compensator', averagePrice: 250, description: 'MP5 compensator.' },
  { name: 'Mosin Compensator', class: 'Mosin_Compensator', averagePrice: 300, description: 'Mosin compensator.' },
  { name: 'AK Bayonet', class: 'AK_Bayonet', averagePrice: 200, description: 'AK bayonet attachment.' },
  { name: 'M9A1 Bayonet', class: 'M9A1_Bayonet', averagePrice: 220, description: 'M9A1 bayonet.' },
  { name: 'Mosin Bayonet', class: 'Mosin_Bayonet', averagePrice: 200, description: 'Mosin bayonet.' },
  { name: 'SKS Bayonet', class: 'SKS_Bayonet', averagePrice: 200, description: 'SKS bayonet.' },
  
  // Weapon Attachments - Buttstocks
  { name: 'AK Folding Buttstock', class: 'AK_FoldingBttstck', averagePrice: 300, description: 'AK folding stock.' },
  { name: 'AK Folding Buttstock (Black)', class: 'AK_FoldingBttstck_Black', averagePrice: 300, description: 'Black AK folding stock.' },
  { name: 'AK Folding Buttstock (Green)', class: 'AK_FoldingBttstck_Green', averagePrice: 300, description: 'Green AK folding stock.' },
  { name: 'AK Plastic Buttstock', class: 'AK_PlasticBttstck', averagePrice: 250, description: 'AK plastic stock.' },
  { name: 'AK Plastic Buttstock (Black)', class: 'AK_PlasticBttstck_Black', averagePrice: 250, description: 'Black AK plastic stock.' },
  { name: 'AK Plastic Buttstock (Green)', class: 'AK_PlasticBttstck_Green', averagePrice: 250, description: 'Green AK plastic stock.' },
  { name: 'AK Wood Buttstock', class: 'AK_WoodBttstck', averagePrice: 280, description: 'AK wood stock.' },
  { name: 'AK Wood Buttstock (Black)', class: 'AK_WoodBttstck_Black', averagePrice: 280, description: 'Black AK wood stock.' },
  { name: 'AK Wood Buttstock (Camo)', class: 'AK_WoodBttstck_Camo', averagePrice: 280, description: 'Camo AK wood stock.' },
  { name: 'AK74 Wood Buttstock', class: 'AK74_WoodBttstck', averagePrice: 280, description: 'AK74 wood stock.' },
  { name: 'AKS74U Buttstock', class: 'AKS74U_Bttstck', averagePrice: 300, description: 'AKS74U stock.' },
  { name: 'FAL Folding Buttstock', class: 'Fal_FoldingBttstck', averagePrice: 350, description: 'FAL folding stock.' },
  { name: 'FAL OE Buttstock', class: 'Fal_OeBttstck', averagePrice: 320, description: 'FAL original equipment stock.' },
  { name: 'M4 CQB Buttstock', class: 'M4_CQBBttstck', averagePrice: 300, description: 'M4 close quarters stock.' },
  { name: 'M4 MP Buttstock', class: 'M4_MPBttstck', averagePrice: 280, description: 'M4 magpul stock.' },
  { name: 'M4 OE Buttstock', class: 'M4_OEBttstck', averagePrice: 250, description: 'M4 original equipment stock.' },
  { name: 'MP5K Stock Buttstock', class: 'MP5k_StockBttstck', averagePrice: 280, description: 'MP5K stock.' },
  { name: 'PP19 Buttstock', class: 'PP19_Bttstck', averagePrice: 250, description: 'PP19 stock.' },
  { name: 'Saiga Buttstock', class: 'Saiga_Bttstck', averagePrice: 280, description: 'Saiga stock.' },
  
  // Weapon Attachments - Handguards
  { name: 'AK Plastic Handguard', class: 'AK_PlasticHndgrd', averagePrice: 200, description: 'AK plastic handguard.' },
  { name: 'AK Rail Handguard', class: 'AK_RailHndgrd', averagePrice: 280, description: 'AK rail handguard.' },
  { name: 'AK Rail Handguard (Black)', class: 'AK_RailHndgrd_Black', averagePrice: 280, description: 'Black AK rail handguard.' },
  { name: 'AK Rail Handguard (Green)', class: 'AK_RailHndgrd_Green', averagePrice: 280, description: 'Green AK rail handguard.' },
  { name: 'AK Wood Handguard', class: 'AK_WoodHndgrd', averagePrice: 220, description: 'AK wood handguard.' },
  { name: 'AK Wood Handguard (Black)', class: 'AK_WoodHndgrd_Black', averagePrice: 220, description: 'Black AK wood handguard.' },
  { name: 'AK Wood Handguard (Camo)', class: 'AK_WoodHndgrd_Camo', averagePrice: 220, description: 'Camo AK wood handguard.' },
  { name: 'AK74 Handguard', class: 'AK74_Hndgrd', averagePrice: 200, description: 'AK74 handguard.' },
  { name: 'M4 MP Handguard', class: 'M4_MPHndgrd', averagePrice: 280, description: 'M4 magpul handguard.' },
  { name: 'M4 Plastic Handguard', class: 'M4_PlasticHndgrd', averagePrice: 200, description: 'M4 plastic handguard.' },
  { name: 'M4 RIS Handguard', class: 'M4_RISHndgrd', averagePrice: 300, description: 'M4 RIS rail handguard.' },
  { name: 'M4 RIS Handguard (Black)', class: 'M4_RISHndgrd_Black', averagePrice: 300, description: 'Black M4 RIS handguard.' },
  { name: 'M4 RIS Handguard (Green)', class: 'M4_RISHndgrd_Green', averagePrice: 300, description: 'Green M4 RIS handguard.' },
  { name: 'MP5 Plastic Handguard', class: 'MP5_PlasticHndgrd', averagePrice: 180, description: 'MP5 plastic handguard.' },
  { name: 'MP5 Rail Handguard', class: 'MP5_RailHndgrd', averagePrice: 250, description: 'MP5 rail handguard.' },
  
  // Weapon Attachments - Lights & Ghillie
  { name: 'Flashlight', class: 'Flashlight', averagePrice: 100, description: 'Weapon flashlight.' },
  { name: 'TLR Light', class: 'TLRLight', averagePrice: 150, description: 'Tactical weapon light.' },
  { name: 'Universal Light', class: 'UniversalLight', averagePrice: 120, description: 'Universal weapon light.' },
  { name: 'Ghillie Attachment (Mossy)', class: 'GhillieAtt_Mossy', averagePrice: 400, description: 'Mossy ghillie wrap.' },
  { name: 'Ghillie Attachment (Tan)', class: 'GhillieAtt_Tan', averagePrice: 400, description: 'Tan ghillie wrap.' },
  { name: 'Ghillie Attachment (Winter)', class: 'GhillieAtt_Winter', averagePrice: 400, description: 'Winter ghillie wrap.' },
  { name: 'Ghillie Attachment (Woodland)', class: 'GhillieAtt_Woodland', averagePrice: 400, description: 'Woodland ghillie wrap.' },

  // Magazines from types.xml
  { name: '1911 Magazine (7Rnd)', class: 'Mag_1911_7Rnd', averagePrice: 200, description: '7-round magazine for 1911 pistol.' },
  { name: 'AK101 Magazine (30Rnd)', class: 'Mag_AK101_30Rnd', averagePrice: 300, description: '30-round magazine for AK101.' },
  { name: 'AK74 Magazine (30Rnd)', class: 'Mag_AK74_30Rnd', averagePrice: 300, description: '30-round magazine for AK74.' },
  { name: 'AK74 Magazine (45Rnd)', class: 'Mag_AK74_45Rnd', averagePrice: 350, description: '45-round magazine for AK74.' },
  { name: 'AKM Magazine (30Rnd)', class: 'Mag_AKM_30Rnd', averagePrice: 300, description: '30-round magazine for AKM.' },
  { name: 'AKM Drum Magazine (75Rnd)', class: 'Mag_AKM_Drum75Rnd', averagePrice: 600, description: '75-round drum magazine for AKM.' },
  { name: 'AKM Palm Magazine (30Rnd)', class: 'Mag_AKM_Palm30Rnd', averagePrice: 320, description: '30-round palm magazine for AKM.' },
  { name: 'AUG Magazine (30Rnd)', class: 'Mag_Aug_30Rnd', averagePrice: 300, description: '30-round magazine for AUG.' },
  { name: 'CMAG (10Rnd)', class: 'Mag_CMAG_10Rnd', averagePrice: 120, description: '10-round CMAG.' },
  { name: 'CMAG (20Rnd)', class: 'Mag_CMAG_20Rnd', averagePrice: 180, description: '20-round CMAG.' },
  { name: 'CMAG (30Rnd)', class: 'Mag_CMAG_30Rnd', averagePrice: 220, description: '30-round CMAG.' },
  { name: 'CMAG (40Rnd)', class: 'Mag_CMAG_40Rnd', averagePrice: 260, description: '40-round CMAG.' },
  { name: 'CZ527 Magazine (5Rnd)', class: 'Mag_CZ527_5rnd', averagePrice: 150, description: '5-round magazine for CZ527.' },
  { name: 'CZ550 Magazine (10Rnd)', class: 'Mag_CZ550_10Rnd', averagePrice: 180, description: '10-round magazine for CZ550.' },
  { name: 'CZ61 Magazine (20Rnd)', class: 'Mag_CZ61_20Rnd', averagePrice: 180, description: '20-round magazine for CZ61.' },
  { name: 'CZ75 Magazine (15Rnd)', class: 'Mag_CZ75_15Rnd', averagePrice: 180, description: '15-round magazine for CZ75.' },
  { name: 'Deagle Magazine (9Rnd)', class: 'Mag_Deagle_9rnd', averagePrice: 200, description: '9-round magazine for Deagle.' },
  { name: 'FAL Magazine (20Rnd)', class: 'Mag_FAL_20Rnd', averagePrice: 350, description: '20-round magazine for FAL.' },
  { name: 'FAMAS Magazine (25Rnd)', class: 'Mag_FAMAS_25Rnd', averagePrice: 320, description: '25-round magazine for FAMAS.' },
  { name: 'FNX45 Magazine (15Rnd)', class: 'Mag_FNX45_15Rnd', averagePrice: 180, description: '15-round magazine for FNX45.' },
  { name: 'Glock Magazine (15Rnd)', class: 'Mag_Glock_15Rnd', averagePrice: 180, description: '15-round magazine for Glock.' },
  { name: 'IJ70 Magazine (8Rnd)', class: 'Mag_IJ70_8Rnd', averagePrice: 120, description: '8-round magazine for IJ70.' },
  { name: 'M14 Magazine (10Rnd)', class: 'Mag_M14_10Rnd', averagePrice: 200, description: '10-round magazine for M14.' },
  { name: 'M14 Magazine (20Rnd)', class: 'Mag_M14_20Rnd', averagePrice: 250, description: '20-round magazine for M14.' },
  { name: 'MKII Magazine (10Rnd)', class: 'Mag_MKII_10Rnd', averagePrice: 120, description: '10-round magazine for MKII.' },
  { name: 'MP5 Magazine (15Rnd)', class: 'Mag_MP5_15Rnd', averagePrice: 150, description: '15-round magazine for MP5.' },
  { name: 'MP5 Magazine (30Rnd)', class: 'Mag_MP5_30Rnd', averagePrice: 200, description: '30-round magazine for MP5.' },
  { name: 'P1 Magazine (8Rnd)', class: 'Mag_P1_8Rnd', averagePrice: 120, description: '8-round magazine for P1.' },
  { name: 'PM73 Magazine (15Rnd)', class: 'Mag_PM73_15Rnd', averagePrice: 150, description: '15-round magazine for PM73.' },
  { name: 'PM73 Magazine (25Rnd)', class: 'Mag_PM73_25Rnd', averagePrice: 180, description: '25-round magazine for PM73.' },
  { name: 'PP19 Magazine (64Rnd)', class: 'Mag_PP19_64Rnd', averagePrice: 400, description: '64-round magazine for PP19.' },
  { name: 'Ruger 10/22 Magazine (15Rnd)', class: 'Mag_Ruger1022_15Rnd', averagePrice: 120, description: '15-round magazine for Ruger 10/22.' },
  { name: 'Ruger 10/22 Magazine (30Rnd)', class: 'Mag_Ruger1022_30Rnd', averagePrice: 180, description: '30-round magazine for Ruger 10/22.' },
  { name: 'SSG82 Magazine (5Rnd)', class: 'Mag_SSG82_5rnd', averagePrice: 150, description: '5-round magazine for SSG82.' },
  { name: 'STANAG Magazine (30Rnd)', class: 'Mag_STANAG_30Rnd', averagePrice: 220, description: '30-round STANAG magazine.' },
  { name: 'STANAG Magazine (60Rnd)', class: 'Mag_STANAG_60Rnd', averagePrice: 350, description: '60-round STANAG magazine.' },
  { name: 'SV98 Magazine (10Rnd)', class: 'Mag_SV98_10Rnd', averagePrice: 200, description: '10-round magazine for SV98.' },
  { name: 'SVD Magazine (10Rnd)', class: 'Mag_SVD_10Rnd', averagePrice: 250, description: '10-round magazine for SVD.' },
  { name: 'Saiga Magazine (5Rnd)', class: 'Mag_Saiga_5Rnd', averagePrice: 180, description: '5-round magazine for Saiga.' },
  { name: 'Saiga Magazine (8Rnd)', class: 'Mag_Saiga_8Rnd', averagePrice: 220, description: '8-round magazine for Saiga.' },
  { name: 'Saiga Drum Magazine (20Rnd)', class: 'Mag_Saiga_Drum20Rnd', averagePrice: 400, description: '20-round drum magazine for Saiga.' },
  { name: 'Scout Magazine (5Rnd)', class: 'Mag_Scout_5Rnd', averagePrice: 150, description: '5-round magazine for Scout.' },
  { name: 'UMP Magazine (25Rnd)', class: 'Mag_UMP_25Rnd', averagePrice: 200, description: '25-round magazine for UMP.' },
  { name: 'VAL Magazine (20Rnd)', class: 'Mag_VAL_20Rnd', averagePrice: 250, description: '20-round magazine for VAL.' },
  { name: 'VSS Magazine (10Rnd)', class: 'Mag_VSS_10Rnd', averagePrice: 200, description: '10-round magazine for VSS.' },
  { name: 'Vikhr Magazine (30Rnd)', class: 'Mag_Vikhr_30Rnd', averagePrice: 300, description: '30-round magazine for Vikhr.' },
  // End magazines
];
