// List of spawnable DayZ items for the shop with average costs (customize as needed)
// Format: { name, class, averagePrice, description }

module.exports = [
  { name: 'M4A1 Assault Rifle', class: 'M4A1', averagePrice: 1200, description: 'Standard 5.56mm assault rifle.' },
  { name: 'AKM', class: 'AKM', averagePrice: 1100, description: '7.62mm classic assault rifle.' },
  { name: 'Mosins Nagant', class: 'Mosin9130', averagePrice: 900, description: 'Bolt-action sniper rifle.' },
  { name: 'SVD', class: 'SVD', averagePrice: 2000, description: 'Rare semi-auto sniper rifle.' },
  { name: 'LAR', class: 'FAL', averagePrice: 1800, description: 'Battle rifle, high damage.' },
  { name: 'M70 Tundra', class: 'M70', averagePrice: 950, description: 'Hunting bolt-action rifle.' },
  { name: 'BK-133 Shotgun', class: 'Mp133', averagePrice: 600, description: 'Pump-action shotgun.' },
  { name: 'BK-18', class: 'BK18', averagePrice: 350, description: 'Single-shot rifle.' },
  { name: 'CR-527', class: 'CZ527', averagePrice: 800, description: 'Bolt-action carbine.' },
  { name: 'USG-45', class: 'UMP45', averagePrice: 850, description: '45 ACP submachine gun.' },
  { name: 'SG5-K', class: 'MP5K', averagePrice: 800, description: '9mm submachine gun.' },
  { name: 'Mlock-19', class: 'Mlock', averagePrice: 400, description: '9mm semi-auto pistol.' },
  { name: 'IJ-70', class: 'IJ70', averagePrice: 300, description: '9mm budget pistol.' },
  { name: 'FX-45', class: 'FNX45', averagePrice: 450, description: '45 ACP pistol.' },
  { name: 'Ammo Box (5.56x45)', class: 'Ammo_556x45', averagePrice: 200, description: 'Box of 5.56mm ammo.' },
  { name: 'Ammo Box (7.62x39)', class: 'Ammo_762x39', averagePrice: 220, description: 'Box of 7.62x39mm ammo.' },
  { name: 'Ammo Box (7.62x54R)', class: 'Ammo_762x54', averagePrice: 250, description: 'Box of 7.62x54R ammo.' },
  { name: 'Ammo Box (9x19mm)', class: 'Ammo_9x19', averagePrice: 120, description: 'Box of 9x19mm ammo.' },
  { name: 'Ammo Box (.45 ACP)', class: 'Ammo_45ACP', averagePrice: 130, description: 'Box of .45 ACP ammo.' },
  { name: 'Plate Carrier', class: 'PlateCarrierVest', averagePrice: 1500, description: 'Heavy armor vest.' },
  { name: 'Assault Backpack', class: 'AssaultBag', averagePrice: 700, description: 'Large capacity backpack.' },
  { name: 'Field Backpack', class: 'FieldBag', averagePrice: 600, description: 'Medium capacity backpack.' },
  { name: 'Hunting Backpack', class: 'HuntingBag', averagePrice: 650, description: 'Hunting backpack.' },
  { name: 'Combat Helmet', class: 'CombatHelmet', averagePrice: 500, description: 'Ballistic helmet.' },
  { name: 'Tactical Gloves', class: 'TacticalGloves_Black', averagePrice: 150, description: 'Protective gloves.' },
  { name: 'NVG Headstrap', class: 'NVGHeadstrap', averagePrice: 2000, description: 'Night vision headstrap.' },
  { name: 'Night Vision Goggles', class: 'NVGoggles', averagePrice: 3500, description: 'Night vision goggles.' },
  { name: 'Canteen', class: 'Canteen', averagePrice: 80, description: 'Water container.' },
  { name: 'Tetracycline Pills', class: 'TetracyclineAntibiotics', averagePrice: 120, description: 'Antibiotic pills.' },
  { name: 'Epinephrine Auto-Injector', class: 'Epinephrine', averagePrice: 180, description: 'Revives unconscious players.' },
  { name: 'Morphine Auto-Injector', class: 'Morphine', averagePrice: 200, description: 'Heals broken bones.' },
  { name: 'Saline Bag IV', class: 'SalineBagIV', averagePrice: 250, description: 'Restores blood.' },
  { name: 'Bandage', class: 'BandageDressing', averagePrice: 60, description: 'Medical bandage.' },
  { name: 'Lockpick', class: 'Lockpick', averagePrice: 100, description: 'Used to lock doors.' },
  { name: 'Car Battery', class: 'CarBattery', averagePrice: 400, description: 'Vehicle battery.' },
  { name: 'Spark Plug', class: 'SparkPlug', averagePrice: 120, description: 'Vehicle spark plug.' },
  { name: 'Radiator', class: 'CarRadiator', averagePrice: 350, description: 'Vehicle radiator.' },
  { name: 'Jerrycan', class: 'CanisterGasoline', averagePrice: 200, description: 'Fuel container.' }
];
